const games=[
 {title:'Cyberpunk 2077',short:'CYBERPUNK',fps:48,set:'Medium',grade:'Good',img:'cp',gpu:'91%',vram:'6.1 GB',cpu:'64%'},
 {title:'GTA V',short:'GTA V',fps:92,set:'Very High',grade:'Excellent',img:'gta',gpu:'78%',vram:'4.8 GB',cpu:'52%'},
 {title:'Minecraft',short:'MINECRAFT',fps:180,set:'High',grade:'Excellent',img:'mc',gpu:'43%',vram:'2.1 GB',cpu:'38%'},
 {title:'Fortnite',short:'FORTNITE',fps:76,set:'High',grade:'Great',img:'fort',gpu:'62%',vram:'3.4 GB',cpu:'48%'},
 {title:'Valorant',short:'VALORANT',fps:120,fps2:'',set:'High',grade:'Excellent',img:'val',gpu:'55%',vram:'2.8 GB',cpu:'42%'},
 {title:'Forza Horizon 5',short:'FORZA',fps:65,set:'High',grade:'Good',img:'forza',gpu:'76%',vram:'4.2 GB',cpu:'58%'},
 {title:'Call of Duty: Warzone',short:'WARZONE',fps:52,set:'Medium',grade:'Good',img:'cod',gpu:'88%',vram:'5.6 GB',cpu:'61%'},
 {title:'Red Dead Redemption 2',short:'RDR2',fps:46,set:'Medium',grade:'Good',img:'rdr',gpu:'82%',vram:'5.1 GB',cpu:'57%'}
];
const nav=[['home','⌂','Home'],['pc','▣','My PC'],['games','🎮','Games'],['compare','⚖','Compare'],['upgrade','↗','Upgrade Path'],['benchmarks','▥','Benchmarks'],['builds','▤','Builds'],['community','♟','Community'],['profile','◉','Profile & Settings']];
let current='home';
const content=document.getElementById('content');
const navEl=document.getElementById('mainNav');
const toastEl=document.getElementById('toast');
navEl.innerHTML=nav.map(([id,ico,label])=>`<button data-route="${id}" class="${id===current?'active':''}"><span class="ico">${ico}</span><span class="label">${label}</span></button>`).join('');
navEl.addEventListener('click',e=>{const b=e.target.closest('[data-route]');if(!b)return;route(b.dataset.route)});
function toast(msg='Done!'){toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1800)}
function esc(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function route(r){current=r;document.querySelectorAll('[data-route]').forEach(x=>x.classList.toggle('active',x.dataset.route===r));render();document.querySelector('.sidebar')?.classList.remove('open');window.scrollTo(0,0)}
function header(ey,title,sub,actions=''){return `<div class="page-head"><div><div class="eyebrow">${ey}</div><div class="page-title">${title}</div><div class="page-sub">${sub}</div></div><div>${actions}</div></div>`}
function gameCards(filter=''){const arr=games.filter(g=>g.title.toLowerCase().includes(filter.toLowerCase()));return `<div class="grid g4">${arr.map(g=>`<div class="card game-card"><div class="game-img" style="background:linear-gradient(135deg,${gameGrad(g.img)})">${g.short}</div><div class="game-body"><div class="game-title">${g.title}</div><div class="tags"><span class="tag">1080p</span><span class="tag">${g.set}</span><span class="tag good">${g.grade}</span></div><div class="fps">${g.fps}<span class="small muted"> FPS</span></div><div class="small muted">GPU ${g.gpu} · VRAM ${g.vram} · CPU ${g.cpu}</div></div></div>`).join('')}</div>`}
function gameGrad(k){const m={cp:'#4d2437,#171727',gta:'#a96a25,#243848',mc:'#285d3a,#5f3d2a',fort:'#3a3f81,#7b2d80',val:'#6e2e50,#192e4c',forza:'#2f6687,#7d321d',cod:'#2d3949,#1a1f28',rdr:'#8c3b25,#271c1c'};return m[k]||'#1b3550,#0d1a29'}
function render(){switch(current){case'home':return renderHome();case'pc':return renderPC();case'games':return renderGames();case'compare':return renderCompare();case'upgrade':return renderUpgrade();case'benchmarks':return renderBench();case'builds':return renderBuilds();case'community':return renderCommunity();case'profile':return renderProfile()}}
function renderHome(){content.innerHTML=`${header('PCPlayground','Know Your PC.','See what you can run, find your bottlenecks, and plan your next upgrade.','<button class="btn btn-primary" data-action="toast">Analyze My PC →</button>')}
<div class="card hero"><div><div class="eyebrow">Your current setup</div><h1>Performance without the guesswork.</h1><p>Turn your hardware into useful answers: estimated FPS, recommended settings, bottlenecks, power draw, and upgrade paths.</p><div class="spec-pills"><span class="spec-pill">16GB RAM</span><span class="spec-pill">RX 580 8GB</span><span class="spec-pill">Ryzen 5 2600</span><span class="spec-pill">256GB NVMe + 1TB HDD</span></div></div><div class="pc-art"><div class="case"><div class="fan"></div></div></div></div>
<div class="grid g3" style="margin-top:12px"><div class="card pad score"><div class="ring"><span>72</span></div><div><div class="section-title">Overall performance</div><div class="muted small">Your PC is capable of gaming at 1080p with sensible settings.</div></div></div><div class="card pad"><div class="section-title">Bottleneck analysis</div><div style="color:var(--yellow);font-weight:700;font-size:12px">⚠ GPU Limited</div><div class="muted small" style="margin:7px 0 10px">RX 580 is the main limiter in modern games.</div><button class="btn" data-route="upgrade">View details</button></div><div class="card pad"><div class="section-title">Estimated power draw</div><div style="font-size:24px;font-weight:800">~320 W</div><div class="bar" style="margin:9px 0"><span style="width:53%"></span></div><div class="small muted">CPU 65W · GPU 185W · Other 70W</div></div></div>
<div style="margin-top:14px" class="section-title">What Can I Run?</div>${gameCards()}`;wireRouteButtons()}
function renderPC(){content.innerHTML=`${header('My PC','Your build','Manage your parts and see how every component affects performance.','<button class="btn btn-primary" data-action="toast">Save Build</button>')}<div class="grid g2"><div class="card pad"><div class="section-title">Core components</div>${[['CPU','Ryzen 5 2600','6 Cores / 12 Threads'],['GPU','MSI RX 580 8GB','8 GB GDDR5'],['RAM','16 GB DDR4 3200 MHz','2 × 8 GB'],['Storage','256 GB NVMe + 1 TB HDD','~ 1.1 TB total'],['PSU','600 W','80+ Bronze'],['Monitor','1080p · 60 Hz','Standard display']].map(x=>`<div class="step"><div class="rank">▣</div><div><b>${x[0]}</b><div class="small muted">${x[2]}</div></div><div>${x[1]}</div></div>`).join('')}</div><div class="card pad"><div class="section-title">Performance breakdown</div><div class="grid g2">${[['CPU','68'],['GPU','74'],['RAM','82'],['Storage','76']].map(x=>`<div class="metric"><span class="small muted">${x[0]}</span><b>${x[1]}/100</b><div class="bar" style="margin-top:7px"><span style="width:${x[1]}%"></span></div></div>`).join('')}</div><div class="section-title" style="margin-top:16px">Power budget</div><div class="bar"><span style="width:53%"></span></div><div class="small muted" style="margin-top:6px">Estimated system draw ~320 W / 600 W PSU</div></div></div>`}
function renderGames(){content.innerHTML=`${header('Games','What can I run?','Browse estimated performance for popular games and find the right settings.')}<div class="filters"><input class="input" id="gameSearch" placeholder="Search games..."/><select class="input"><option>1080p</option><option>1440p</option><option>4K</option></select><select class="input"><option>60 FPS</option><option>120 FPS</option><option>144 FPS</option></select><select class="input"><option>High</option><option>Medium</option><option>Ultra</option></select></div><div id="gamesGrid">${gameCards()}</div>`;document.getElementById('gameSearch').addEventListener('input',e=>document.getElementById('gamesGrid').innerHTML=gameCards(e.target.value))}
function renderCompare(){content.innerHTML=`${header('Compare','Compare builds','See exactly what changes when you swap components.','<button class="btn btn-primary" data-action="toast">Share Comparison</button>')}<div class="card pad"><div class="grid g2"><div><div class="section-title">Your Build</div><div class="metric-grid"><div class="metric"><span class="small muted">CPU</span><b>R5 2600</b></div><div class="metric"><span class="small muted">GPU</span><b>RX 580</b></div><div class="metric"><span class="small muted">RAM</span><b>16GB</b></div><div class="metric"><span class="small muted">Drive</span><b>NVMe</b></div></div></div><div><div class="section-title">Build B</div><div class="metric-grid"><div class="metric"><span class="small muted">CPU</span><b>R5 5600</b></div><div class="metric"><span class="small muted">GPU</span><b>RTX 4060</b></div><div class="metric"><span class="small muted">RAM</span><b>16GB</b></div><div class="metric"><span class="small muted">Drive</span><b>1TB SSD</b></div></div></div></div><table class="table" style="margin-top:15px"><thead><tr><th>Game</th><th>Your PC</th><th>Build B</th><th>Difference</th></tr></thead><tbody>${[['GTA V',92,156,'+70%'],['Minecraft',180,300,'+67%'],['Cyberpunk 2077',48,86,'+79%'],['Fortnite',76,132,'+74%']].map(r=>`<tr><td>${r[0]}</td><td>${r[1]} FPS</td><td>${r[2]} FPS</td><td class="positive">▲ ${r[3]}</td></tr>`).join('')}</tbody></table></div>`}
function renderUpgrade(){content.innerHTML=`${header('Upgrade Path','Upgrade smarter','Prioritize the changes that actually improve your gaming experience.')}<div class="grid g2"><div class="card pad"><div class="section-title">What should you upgrade first?</div>${[['1','GPU','Highest impact','RX 6600','+72%'],['2','CPU','Moderate impact','Ryzen 5 5600','+48%'],['3','RAM','Low impact','32GB DDR4','+12%']].map(s=>`<div class="step"><div class="stepnum">${s[0]}</div><div><b>${s[1]}</b><div class="small muted">${s[2]} · ${s[3]}</div></div><strong class="positive">${s[4]}</strong></div>`).join('')}</div><div class="card pad"><div class="section-title">Upgrade budget guide</div>${[['₨ 50k','Best value','GPU'],['₨ 100k','Balanced','GPU + CPU'],['₨ 200k+','High-end','Platform refresh']].map(x=>`<div class="metric" style="margin-bottom:8px"><span class="small muted">${x[0]}</span><b>${x[1]}</b><span class="small muted">Focus: ${x[2]}</span></div>`).join('')}</div></div>`}
function renderBench(){content.innerHTML=`${header('Benchmarks','Benchmarks & tests','Run repeatable tests and compare your score with similar hardware.')}<div class="grid g2"><div class="card pad"><div class="tabs"><button class="tab active">CPU</button><button class="tab">GPU</button><button class="tab">Storage</button><button class="tab">Network</button></div><div class="section-title">Cinebench R23</div><div class="metric-grid"><div class="metric"><span class="small muted">Multi-core</span><b>4582</b></div><div class="metric"><span class="small muted">Single-core</span><b>982</b></div></div><button class="btn btn-primary" style="width:100%;margin-top:12px" data-action="toast">Run Test</button></div><div class="card pad"><div class="section-title">Other benchmarks</div>${[['3DMark Time Spy','GPU benchmark'],['Geekbench 6','CPU benchmark'],['SpeedTest','Internet speed'],['CrystalDisk','Storage test']].map(x=>`<div class="step"><div class="rank">●</div><div><b>${x[0]}</b><div class="small muted">${x[1]}</div></div><span>→</span></div>`).join('')}</div></div><div class="card pad" style="margin-top:12px"><div class="section-title">Past results</div><table class="table"><tr><th>Date</th><th>Benchmark</th><th>Score</th></tr><tr><td>2026-08-15</td><td>Cinebench R23</td><td>4582 MC</td></tr><tr><td>2026-08-10</td><td>3DMark Time Spy</td><td>4120</td></tr><tr><td>2026-08-05</td><td>Geekbench 6</td><td>1310 SC</td></tr></table></div>`}
function renderBuilds(){content.innerHTML=`${header('Builds','Build library','Save, publish and compare complete PC configurations.','<button class="btn btn-primary" data-action="toast">+ Create New Build</button>')}<div class="grid g3">${[['Budget Gaming Build','RX 6600 + R5 5600','~95 FPS · 1080p High'],['High Performance','RTX 4060 Ti + R5 7600','~140 FPS · 1080p Ultra'],['Black Stealth','RTX 4070 + R7 7700','~165 FPS · 1440p High'],['Value AM4','RX 6700 XT + R5 5600','~120 FPS · 1080p High'],['Creator Hybrid','RTX 4070 Super + R9 7900','Gaming + Workstation'],['Entry 1080p','RX 6600 + i3 12100F','~80 FPS · 1080p High']].map((b,i)=>`<div class="card pad"><div class="game-img" style="border-radius:9px;margin-bottom:10px;background:linear-gradient(135deg,#0f2840,#12233a)">BUILD ${String(i+1).padStart(2,'0')}</div><b>${b[0]}</b><div class="small muted" style="margin:6px 0">${b[1]}</div><div class="positive small">${b[2]}</div><button class="btn" style="width:100%;margin-top:10px" data-action="toast">View Build</button></div>`).join('')}</div>`}
function renderCommunity(){content.innerHTML=`${header('Community','Community','Share builds, ask questions and compare real-world setups.','<button class="btn btn-primary" data-action="toast">Create Post</button>')}<div class="card"><div class="tabs" style="padding:0 12px"><button class="tab active">Featured Builds</button><button class="tab">Discussions</button><button class="tab">Leaderboard</button></div><div>${[['My 2026 Gaming Build','R5 5600 · RX 6600 · 16GB','312','15'],['Budget Gaming Setup','i3 12100F · RX 6600','1.2k','48'],['Best GPU for RX 580?','Upgrade discussion','856','29'],['My game is lagging, help?','Troubleshooting','633','41'],['Should I upgrade to 32GB?','RAM discussion','502','18']].map(p=>`<div class="post"><div class="post-title">${p[0]}</div><div class="post-meta">${p[1]} · ♡ ${p[2]} · 💬 ${p[3]}</div></div>`).join('')}</div></div>`}
function renderProfile(){content.innerHTML=`${header('Account','Profile & Settings','Manage your account, saved builds and preferences.')}<div class="grid g2"><div class="card pad"><div class="profile-head"><div class="profile-big">K</div><div><div style="font-size:18px;font-weight:800">KhanBaba</div><div class="muted small">@khanbaba#1234 · Level 3</div></div></div><div class="metric-grid" style="margin-top:16px"><div class="metric"><span class="small muted">Builds</span><b>3</b></div><div class="metric"><span class="small muted">Followers</span><b>24</b></div><div class="metric"><span class="small muted">Following</span><b>12</b></div><div class="metric"><span class="small muted">XP</span><b>4,410</b></div></div></div><div class="card pad"><div class="section-title">Settings</div>${[['Email notifications','Get updates and news'],['Game updates','New benchmark/game data'],['Public profile','Let others see your builds'],['Compact cards','Fit more games on screen']].map(x=>`<div class="step"><div class="rank">●</div><div><b>${x[0]}</b><div class="small muted">${x[1]}</div></div><label><input type="checkbox" checked></label></div>`).join('')}</div></div>`}
function wireRouteButtons(){content.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>route(b.dataset.route)));content.querySelectorAll('[data-action="toast"]').forEach(b=>b.addEventListener('click',()=>toast('Action connected — backend can be added next.')))}
content.addEventListener('click',e=>{const r=e.target.closest('[data-route]');if(r)route(r.dataset.route);const a=e.target.closest('[data-action="toast"]');if(a)toast('Action connected — backend can be added next.')});
document.getElementById('mobileMenu').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));
document.getElementById('globalSearch').addEventListener('input',e=>{if(!e.target.value.trim())return;if(current!=='games')route('games');const gs=document.getElementById('gameSearch');if(gs){gs.value=e.target.value;gs.dispatchEvent(new Event('input'))}});
render();

/* Full-stack API bridge --------------------------------------------------- */
const API = (window.PCPLAYGROUND_API || '').replace(/\/$/,'');
const api = async (path, options={}) => {
  const headers = {'content-type':'application/json', ...(options.headers||{})};
  const token = localStorage.getItem('pp_token'); if(token) headers.authorization=`Bearer ${token}`;
  const r=await fetch(`${API}${path}`,{...options,headers}); const data=await r.json().catch(()=>({}));
  if(!r.ok) throw new Error(data.error||`Request failed (${r.status})`); return data;
};
async function hydrateGames(){ if(!API) return; try{ const d=await api('/api/games'); if(d.games?.length){ games.splice(0,games.length,...d.games.map(g=>({title:g.title,short:g.title.toUpperCase().slice(0,12),fps:g.high_fps,set:'High',grade:g.high_fps>=100?'Excellent':g.high_fps>=70?'Great':g.high_fps>=45?'Good':'Playable',img:g.image,gpu:g.gpu_load+'%',vram:g.vram,cpu:g.cpu_load+'%'}))); if(current==='games'||current==='home') render(); } }catch(e){} }
async function saveBuildRemote(build){ if(!API) throw new Error('API is not configured.'); return api('/api/builds',{method:'POST',body:JSON.stringify(build)}); }
async function loadBuildsRemote(){ return api('/api/builds'); }
async function loginRemote(username,password){ const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username,password})}); localStorage.setItem('pp_token',d.token); return d; }
async function registerRemote(username,password){ const d=await api('/api/auth/register',{method:'POST',body:JSON.stringify({username,password})}); localStorage.setItem('pp_token',d.token); return d; }
window.PCPlaygroundAPI={api,saveBuildRemote,loadBuildsRemote,loginRemote,registerRemote};
hydrateGames();

/* Live data UI ------------------------------------------------------------ */
function openAuth(mode='login'){
  const old=document.getElementById('authModal'); if(old) old.remove();
  document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="authModal"><div class="modal"><div class="eyebrow">PCPlayground account</div><h2>${mode==='login'?'Welcome back':'Create your account'}</h2><div class="muted small">${API?'Your data will be stored securely in Cloudflare D1.':'Connect a Cloudflare Worker API in config.js to enable accounts.'}</div><input id="authUser" class="input" placeholder="Username" autocomplete="username"><input id="authPass" class="input" placeholder="Password (8+ characters)" type="password" autocomplete="${mode==='login'?'current-password':'new-password'}"><div class="modal-row"><button class="btn" id="authClose">Cancel</button><button class="btn btn-primary" id="authGo">${mode==='login'?'Log in':'Register'}</button></div><button class="btn" id="authSwitch" style="width:100%;margin-top:8px">${mode==='login'?'Need an account? Register':'Already have an account? Log in'}</button></div></div>`);
  document.getElementById('authClose').onclick=()=>document.getElementById('authModal').remove();
  document.getElementById('authSwitch').onclick=()=>openAuth(mode==='login'?'register':'login');
  document.getElementById('authGo').onclick=async()=>{ const u=document.getElementById('authUser').value.trim(),p=document.getElementById('authPass').value; try{if(!API)throw new Error('Set PCPLAYGROUND_API in config.js first.'); const d=mode==='login'?await loginRemote(u,p):await registerRemote(u,p); toast(`Welcome, ${d.user.username}!`); document.getElementById('authModal').remove(); render();}catch(e){toast(e.message)} };
}
function loggedIn(){return !!localStorage.getItem('pp_token')}

const oldRenderBuilds=renderBuilds;
renderBuilds=async function(){
  content.innerHTML=`${header('Builds','Build library','Your saved PC builds live here.','<button class="btn btn-primary" id="createBuild">+ Create New Build</button>')}<div id="buildStatus" class="card pad"><span class="online-dot">API-ready</span> ${loggedIn()?'Loading your saved builds…':'Log in to save builds to the cloud.'}</div><div id="buildList" class="grid g3"></div>`;
  document.getElementById('createBuild').onclick=()=>{
    if(!loggedIn()){openAuth('login');return}
    const name=prompt('Build name','My Gaming PC'); if(!name)return;
    const build={name,cpu:'Ryzen 5 2600',gpu:'MSI RX 580 8GB',ram:'16 GB DDR4 3200 MHz',storage:'256 GB NVMe + 1 TB HDD',psu:'600 W',monitor:'1080p · 60 Hz',visibility:'private'};
    saveBuildRemote(build).then(()=>{toast('Build saved to Cloudflare D1.');renderBuilds()}).catch(e=>toast(e.message));
  };
  if(!loggedIn()||!API)return;
  try{const d=await loadBuildsRemote();const el=document.getElementById('buildList');el.innerHTML=(d.builds||[]).map(b=>`<div class="card pad"><div class="game-img" style="border-radius:9px;margin-bottom:10px;background:linear-gradient(135deg,#0f2840,#12233a)">BUILD</div><b>${esc(b.name)}</b><div class="small muted" style="margin:6px 0">${esc(b.cpu)} · ${esc(b.gpu)}</div><div class="small muted">${esc(b.ram)} · ${esc(b.storage)}</div><div class="small muted" style="margin-top:6px">${esc(b.visibility)} · saved ${esc(b.updated_at||b.created_at||'')}</div><button class="btn" style="width:100%;margin-top:10px" onclick="deleteBuild(${b.id})">Delete</button></div>`).join('')||`<div class="card pad muted">No builds yet. Create your first one.</div>`;
  }catch(e){document.getElementById('buildStatus').innerHTML=`<span class="muted">${esc(e.message)}</span>`}
};
window.deleteBuild=async(id)=>{try{await api('/api/builds/'+id,{method:'DELETE'});toast('Build deleted.');renderBuilds()}catch(e){toast(e.message)}};

const oldRenderCommunity=renderCommunity;
renderCommunity=async function(){
  content.innerHTML=`${header('Community','Community','Share builds, ask questions and compare real-world setups.','<button class="btn btn-primary" id="createPost">Create Post</button>')}<div id="postList" class="card"></div>`;
  document.getElementById('createPost').onclick=async()=>{if(!loggedIn()){openAuth('login');return} const title=prompt('Post title'); if(!title)return; const text=prompt('Post body','Tell the community about your PC.'); if(!text)return; try{await api('/api/posts',{method:'POST',body:JSON.stringify({title,body:text})});toast('Post published.');renderCommunity()}catch(e){toast(e.message)}};
  if(!API){document.getElementById('postList').innerHTML='<div class="pad muted">Connect the Cloudflare API in config.js to load community posts.</div>';return}
  try{const d=await api('/api/posts');document.getElementById('postList').innerHTML=(d.posts||[]).map(p=>`<div class="post"><div class="post-title">${esc(p.title)}</div><div class="post-meta">@${esc(p.username||'member')} · ${esc(p.created_at||'')}</div><div class="small" style="margin-top:6px">${esc(p.body)}</div></div>`).join('')||'<div class="pad muted">No posts yet. Be the first.</div>'}catch(e){document.getElementById('postList').innerHTML=`<div class="pad muted">${esc(e.message)}</div>`}
};

const oldRenderProfile=renderProfile;
renderProfile=function(){
  if(!loggedIn()){content.innerHTML=`${header('Account','Profile & Settings','Create an account to sync builds and community activity.','<button class="btn btn-primary" id="loginBtn">Log in</button>')}<div class="card pad"><div class="profile-head"><div class="profile-big">?</div><div><div style="font-size:18px;font-weight:800">Guest</div><div class="muted small">Your local browser data stays on this device.</div></div></div><button class="btn btn-primary" id="registerBtn" style="margin-top:16px">Create account</button></div>`;document.getElementById('loginBtn').onclick=()=>openAuth('login');document.getElementById('registerBtn').onclick=()=>openAuth('register');return}
  content.innerHTML=`${header('Account','Profile & Settings','Your PCPlayground account and preferences.','<button class="btn" id="logoutBtn">Log out</button>')}<div class="grid g2"><div class="card pad"><div class="profile-head"><div class="profile-big">K</div><div><div style="font-size:18px;font-weight:800">Cloud account</div><div class="muted small">Your account is authenticated with a 30-day session.</div></div></div><div style="margin-top:14px" class="online-dot">Cloud sync enabled</div></div><div class="card pad"><div class="section-title">Settings</div><div class="step"><div><b>Email notifications</b><div class="small muted">Get updates and news</div></div><input type="checkbox"></div><div class="step"><div><b>Public profile</b><div class="small muted">Let others see published builds</div></div><input type="checkbox"></div></div></div>`;document.getElementById('logoutBtn').onclick=()=>{localStorage.removeItem('pp_token');toast('Logged out.');render()};
};

// Re-render after startup game hydration so pages use the live catalog where available.
setTimeout(()=>{if(API && (current==='home'||current==='games')) render()},250);
